# Generated by Django 4.1.7 on 2023-02-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0006_alter_question_content_alter_question_subject_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="contetn",
            new_name="content",
        ),
    ]
